#!/usr/bin/env python

import os
import subprocess
import sys
from pathlib import Path

SRC_DIRS = (".",)
EXTENSIONS = (".RKT",)
EXCLUDE = (".git",)

for dir in SRC_DIRS:
    for root, dirs, files in os.walk(Path(dir).resolve()):
        for ex in EXCLUDE:
            if ex in dirs:
                dirs.remove(ex)
        for name in files:
            if Path(name).suffix.upper() in EXTENSIONS:
                target = Path(root) / name
                subprocess.run(["raco", "fmt", "-i", target])
                if len(sys.argv) > 1 and sys.argv[1] == "-v":
                    print(target.relative_to(os.getcwd()))
