#lang racket/base

(require rackunit
         racket/match
         (prefix-in helpers: "helpers.rkt"))

(define (block-check fn data-block [message ""] [print? #f])
  (for ([i data-block])
    (match-define (list in out) i)
    (check-equal? (apply fn in) out message)
    (when print?
      (printf "~v ~v\n" in out))))

(define plus-block '(((2 2) 4) ((3 4) 7) ((1 1 1) 3)))
(block-check + plus-block "+" #t)

(check-equal? (regexp-split #px"[\\s.]+" "") '("") "Split an empty string on something")

(check-equal? (regexp-replace* #px"[\\s.\\-]+" " . .. \t - . -- .. -- -" "")
              ""
              "Remove all spaces, dots, and dashes")

(define initials-block
  '((("") "") ((" ") "")
              ((".. , .. ") "")
              ((" ,, .,") "")
              (("l") "L.")
              ((", a. g, ") "A.G.")
              (("- , -I.V.-A,E.C.N-, .") "I.V-A.,E.C.N.")
              (("  e.B.Sledge ") "E.B.S.")
              (("Apsley Cherry-Garrard") "A.C-G.")
              (("Windsor Saxe-\tCoburg - Gotha") "W.S-C-G.")
              (("Elisabeth Kubler-- - Ross") "E.K-R.")
              (("  Fitz-Simmons Ashton-Burke Leigh") "F-S.A-B.L.")
              (("Arleigh \"31-knot\"Burke ") "A.B.")
              (("Harry\"Bing\"Crosby, Kris \"Tanto\" Paronto") "H.C.,K.P.")
              (("William J. \"Wild Bill\" Donovan, Marta \"Cinta Gonzalez") "W.J.D.,M.C.G.")
              (("a.s , - . ,b.s.") "A.S.,B.S.")
              (("A. Strugatsky, B...Strugatsky.") "A.S.,B.S.")
              (("Иржи Кропачек,, Йозеф Новотный") "И.К.,Й.Н.")
              (("Jason dinAlt") "J.dinA.")
              (("Язон динАльт, Шарль д'Артаньян") "Я.динА.,Ш.д'А.")
              (("Charles de Batz de Castelmore d'Artagnan") "C.d.B.d.C.d'A.")
              (("Mario Del Monaco, Hutchinson of London") "M.D.M.,H.o.L.")
              (("Anselm haut Rodric") "A.h.R.")
              (("Ансельм от Родрик") "А.о.Р.")
              (("Leonardo Wilhelm DiCaprio") "L.W.DiC.")
              (("леонардо вильгельм ди каприо") "Л.В.д.К.")
              (("kapitän zur see") "K.z.S.")
              (("De Beers, Guido van Rossum") "D.B.,G.v.R.")
              (("Манфред фон Рихтгофен") "М.ф.Р.")
              (("Armand Jean du Plessis") "A.J.d.P.")
              (("johannes diderik van der waals") "J.D.v.d.W.")
              (("Karl Hård af Segerstad") "K.H.a.S.")
              (("Österreich über alles") "Ö.Ü.A.")
              (("José Eduardo dos Santos") "J.E.d.S.")
              (("Gnda'Ke") "Gnda'K.")
              (("gnda'ke") "gnda'k.") ;(("gnda'ke") "G.")
              (("gnda'") "G.")
              (("'Bravo") "'B.")
              (("'") "'.")
              (("'B") "'B.")
              (("'b") "'b.")
              (("dA") "D.") ;(("dA") "dA.")
              (("DA") "D.") ;(("DA") "DA.")
              (("DAMadar") "DA.")
              (("Плиний Старший") "П.Ст.")
              (("Pliny the Elder") "P.t.E.")
              (("Плиний Младший") "П.Мл.")
              (("Плиний Мл.") "П.Мл.")
              (("George Smith Patton Jr.") "G.S.P.Jr.")
              (("Джордж Смит паттон ст") "Д.С.П.ст.")
              (("Redington Sr") "R.Sr.")
              (("John ronald reuel Tolkien") "J.R.R.T.")))
(block-check helpers:initials initials-block "initials" #t)

(define human-fine-block
  '(((0) "0") ((1) "1")
              ((42) "42")
              ((1024) "1kB")
              ((1200) "1kB")
              ((1800) "2kB")
              ((123456789) "117.7MB")
              ((1073741824) "1.00GB")
              ((123456789123) "114.98GB")))
(block-check helpers:human-fine human-fine-block "human-fine" #t)

(check-equal? (helpers:human-fine (expt 1024 2)) "1.0MB" "(human-fine (expt 1024 2))")
(check-equal? (helpers:human-fine (expt 1024 3)) "1.00GB" "(human-fine (expt 1024 3))")
(check-equal? (helpers:human-fine (expt 1024 4)) "1.00TB" "(human-fine (expt 1024 4))")
(check-equal? (helpers:human-fine (expt 1024 5)) "1.00PB" "(human-fine (expt 1024 5))")
